# -*- coding: utf-8 -*-
"""STA307 Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JejX37rDv76bqhy8xP0Q_Q5wBwML4gtG
"""

!pip3 install -U ucimlrepo;

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from ucimlrepo import fetch_ucirepo
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
from sklearn.metrics import accuracy_score, ConfusionMatrixDisplay
from sklearn.model_selection import LeaveOneOut, cross_validate, GridSearchCV
from sklearn.tree import DecisionTreeClassifier as DTC
from sklearn.ensemble import RandomForestClassifier as RF

# fetch dataset
cdc_diabetes_health_indicators = fetch_ucirepo(id=891)

# data (as pandas dataframes)
X = cdc_diabetes_health_indicators.data.features
y = cdc_diabetes_health_indicators.data.targets

# metadata
print(cdc_diabetes_health_indicators.metadata)

# variable information
print(cdc_diabetes_health_indicators.variables)

"""## Milestone 1"""

types_of_var = cdc_diabetes_health_indicators.variables.type[2:]
# getting rid of ID and Diabetes_binary with [2:] since they are not included in X, the features

number_of_qualitative = 0
number_of_quantitative = 0
index = 0

varQualitative = np.empty(len(X)).tolist()
varQuantitative = np.empty(len(X)).tolist()

# print(X.columns)
# print(cdc_diabetes_health_indicators.variables)

# demonstrate qualitative/quantitative variables:
for i in types_of_var:
  varName = X.columns[index]

  if (i == "Categorical" or i == "Binary"):
    varQualitative[number_of_qualitative] = varName
    number_of_qualitative += 1
    index += 1
  else:
    varQuantitative[number_of_quantitative] = varName
    number_of_quantitative += 1
    index += 1

# shrink the lists so they don't have empty values:
varQualitative = varQualitative[:number_of_qualitative]
varQuantitative = varQuantitative[:number_of_quantitative]

print(f"Number of qualitative variables: {number_of_qualitative}")
print(varQualitative)

print(f"Number of quantitative variables: {number_of_quantitative}")
print(varQuantitative)

# One interesting qualitative feature: HighChol
print(f"\n\nNumber of patients in the dataset: {X.shape[0]}")
print(X.HighChol.value_counts())

"""## Milestone 2"""

# Aim to predict the binary value indicating having or not having diabetes.

for name in varQuantitative:
  min = np.min(X[name])
  max = np.max(X[name])
  mean = np.mean(X[name])
  median = np.median(X[name])
  std = np.std(X[name])
  print(f"{name}:\n Min: {min:.2f}\n Max: {max:.2f}\n Mean: {mean:.2f}\n Median: {median:.2f}\n STD: {std:.2f}")

# Part 1: KNN
n_neighbors = 100
tryingToFixY = y.values.ravel()
featureData = X[["BMI", "Age"]].values

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(featureData, tryingToFixY, test_size=0.2, random_state=42)

# Initialize KNN classifier
knn = KNeighborsClassifier(n_neighbors=n_neighbors)

# Train the model
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

# decision boundary:
x_min, x_max = featureData[:, 0].min() - 1, featureData[:, 0].max() + 1
y_min, y_max = featureData[:, 1].min() - 1, featureData[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.1),
                     np.arange(y_min, y_max, 0.1))

XX = np.c_[xx.ravel(), yy.ravel()]
Z = knn.predict(XX)
Z = Z.reshape(xx.shape)

fig,ax = plt.subplots(layout="constrained")

# testing accuracy:
testing_accuracy = np.sum(y_test == y_pred)/len(y_test)
print(testing_accuracy)

### Plot the predictions throughout feature space
plt.contourf(xx, yy, Z, alpha=0.3)

# Part 2:

### Plot all data points, with their true classes
scatter = plt.scatter(featureData[:, 0], featureData[:, 1], c=tryingToFixY, edgecolors='k')
plt.xlabel('BMI',fontsize=20)
plt.ylabel('Age (13-level age category)',fontsize=20)
plt.title(f"BMI and Age KNN, N = {n_neighbors}",fontsize=20)

legend1 = ax.legend(*scatter.legend_elements(), loc="lower right",
                    title="Binary Diabetes\nIndication",fontsize=20*.75)
ax.add_artist(legend1)

# Work from office hours to investigate dataset:

# y_test_pred = knn.predict(X_test)
# test_accuracy = np.sum(y_test == y_test_pred)/len(y_test)

# y_train_pred = knn.predict(X_train)
# train_accuracy = np.sum(y_train == y_train_pred)/len(y_train)

print(featureData.shape)

print(np.sum(y==0)/len(y))
print(np.sum(y==1)/len(y))

# Part 3: PCA

#Standardize the data to have mean 0 and variance 1
scaler = StandardScaler()
scaler.fit(X)
X_standardized = scaler.transform(X)

print("Means: ",np.mean(X_standardized,axis=0))
print("Standard deviations: ",np.std(X_standardized,axis=0))
# Means are roughly equal to 0, and all STD are 1.

num_components = 2
pca = PCA(n_components=num_components)

# Fit the PCA model to the standardized data and transform the data
X_reduced = pca.fit_transform(X_standardized)
print("Reduced data size:", X_reduced.shape)

#principal components
components = pca.components_

### plot the principal components
fig,axes = plt.subplots(1,2,layout="constrained",figsize=(20,10))
fontsize=15

axes[0].bar(np.arange(21),components[0,:],color="blue", label = "Principal component 1")
axes[1].bar(np.arange(21),components[1,:],color="red", label = "Principal component 2")

axes[0].set_xticks(ticks = np.arange(21),labels=X.columns,rotation=90,fontsize=20*0.75);
axes[1].set_xticks(ticks = np.arange(21),labels=X.columns,rotation=90,fontsize=20*0.75);
axes[0].set_ylabel("Loading values",fontsize=20)

axes[0].set_title("1st principal component",fontsize=20)
axes[1].set_title("2nd principal component",fontsize=20)

### Look into explained variance
explained_variance = pca.explained_variance_ratio_
cumulative_explained_variance = np.sum(explained_variance)
print(f"Proportion of variance explained by 1st PC: {explained_variance[0]:.3f}")
print(f"Proportion of variance explained by 2nd PC: {explained_variance[1]:.3f}")
print()
print(f"Cumulative proportion of variance explained by first two PCs: {cumulative_explained_variance:.3f}")

### Plot dimensionality-reduced data
fig,ax = plt.subplots()
scatter = ax.scatter(X_reduced[:, 0], X_reduced[:, 1], c=tryingToFixY, edgecolors='k')

ax.set_xlabel('Principal component (PC) 1',fontsize=20)
ax.set_ylabel('Principal component (PC) 2',fontsize=20)
ax.set_title("The dimensionality-reduced Diabetes Indicator dataset",fontsize=20)

# produce a legend with the unique colors from the scatter
legend1 = ax.legend(*scatter.legend_elements(),
                    title="Classes")
ax.add_artist(legend1)

"""## Milestone 3"""

# 1.)
print(f"Number of class 0's: {len(y[y['Diabetes_binary']==0])}")
print(f"Number of class 1's: {len(y[y['Diabetes_binary']==1])}")

## mcc = "most common class"
mcc = y[y['Diabetes_binary']==0]

testing_accuracy = (len(mcc)/len(y))
print(testing_accuracy)

# 2.)
# Using BMI and Age

features = np.transpose([X['BMI'],X['Age']])
cv = 5

# fixing an error:
y = np.ravel(y)

# cv_err = cross_validate(lda,features,y,cv=cv,scoring="accuracy")

# LDA
lda = LDA()
cv_err_LDA = cross_validate(lda,features,y,cv=cv,scoring="accuracy")
LDAaccuracy = np.mean(cv_err_LDA['test_score'])

print(f"LDA Accuracy: {LDAaccuracy}")

# QDA
qda = QDA()
cv_err_QDA = cross_validate(qda,features,y,cv=cv,scoring="accuracy")
QDAaccuracy = np.mean(cv_err_QDA['test_score'])

print(f"QDA Accuracy: {QDAaccuracy}")

# KNN // this one takes a few minutes to execute
n_neighbors = 100
knn = KNeighborsClassifier(n_neighbors=n_neighbors)
cv_err_KNN = cross_validate(knn,features,y,cv=cv,scoring="accuracy")
KNNaccuracy = np.mean(cv_err_KNN['test_score'])

print(f"KNN Accuracy: {KNNaccuracy}")

# testing code to see why accuracy is all the same

# lda = LDA()
# lda.fit(features,y)
# np.sum(lda.predict(features) != 0)

features = np.transpose([X['BMI'],X['Age']])
cv = 5

# fixing an error:
y = np.ravel(y)

# Fit random forest
rf = RF(max_features='sqrt', random_state=42)
cv_err_RF = cross_validate(rf,features,y,cv=cv,scoring="accuracy")
RFaccuracy = np.mean(cv_err_RF['test_score'])

print(f"Random Forest Accuracy: {RFaccuracy}")

# 3.)
features = np.transpose([X['BMI'],X['Age']])

knn = KNeighborsClassifier(n_neighbors=100)
knn.fit(features,y)

x_min, x_max = features[:, 0].min() - 1, features[:, 0].max() + 1
y_min, y_max = features[:, 1].min() - 1, features[:, 1].max() + 1
xx, yy = np.meshgrid(np.linspace(x_min, x_max, 100),
                     np.linspace(y_min, y_max, 100))
XX = np.c_[xx.ravel(), yy.ravel()]

Zknn = knn.predict(XX)
Zknn = Zknn.reshape(xx.shape)

plt.contourf(xx, yy, Zknn, alpha=0.3)
plt.scatter(features[:, 0], features[:, 1], c=y, edgecolors='k')
plt.title("KNN with k=100, for features BMI and Age")
plt.xlabel("BMI")
plt.ylabel("Age, based on 13-level age categorization")
plt.legend(*scatter.legend_elements(),
            title="Binary Diabetes Indicator",
            loc="lower right")